### ISSUE TITLE
biobox.yaml input directory

### ISSUE THREAD

**Issue by pbelmann** [CAMI-challenge/docker_profiling_tools#1]
biobox.yaml should be placed in `/bbx/mnt/input`

https://github.com/sjanssen2/docker_profiling_tools/blob/master/metaphyler/Dockerfile_metaphyler#L47

see
https://github.com/pbelmann/rfc/blob/feature/new-profiling-inteface/container/profiling/rfc.mkd#mounts

**Comment by sjanssen2** [comment]
Changed the ENV YAML in all dockerfiles to /bbx/mnt/input/biobox.yaml
