### ISSUE TITLE
profiling biobox schema

### ISSUE THREAD

**Issue by pbelmann** [CAMI-challenge/docker_profiling_tools#2]
Profiling biobox should check the biobox.yaml against a schema.

The profiling biobox should include the biobox-file-validator binary (e.g: https://github.com/bioboxes/velvet/blob/master/Dockerfile#L17-L31 ) and the [schema](https://github.com/pbelmann/rfc/blob/feature/new-profiling-inteface/container/profiling/schema.yaml). 
It must check the input biobox.yaml against the schema (e.g:https://github.com/bioboxes/velvet/blob/master/assemble#L18-L20 ).

**Comment by sjanssen2** [comment]
Dockerfiles now contain the download and extraction of the validator binary. Utils.pm takes care that the yaml file will be validated prior to task execution.
task.pl will die, if exit code of the validator is != 0.
