### ISSUE TITLE
metaphyler should produce an output biobox.yaml

### ISSUE THREAD

**Issue by pbelmann** [CAMI-challenge/docker_profiling_tools#3]
Every biobox must produce an output biobox.yaml:
(see  https://github.com/pbelmann/rfc/blob/feature/new-profiling-inteface/container/profiling/rfc.mkd#general-definition-1) 

Assembler example in bash: https://github.com/bioboxes/velvet/blob/master/assemble#L52-L59

**Comment by sjanssen2** [comment]
Three questions:
1. what version number should my program report? 1.0.0 ?
2. the input yaml holds a list of input files, each will produce its own profile. Do I get it right, that for the output yaml arguments->profiling-> is a list? Otherwise, do you want to have multiple yaml output files, each holding the path to one profile?
3. If possible, I also copy the original output file of the tools into the mounted output directory. Useful if you don't trust my conversion into a profile. Should that be integrated into the yaml, or do we ignore that, because it is mainly for debugging purpose?

**Comment by pbelmann** [comment]
> Three questions:
> 1.what version number should my program report? 1.0.0 ?

Yes

> 2.the input yaml holds a list of input files, each will produce its own profile. Do I get it right, that for the output yaml arguments->profiling-> is a list? Otherwise, do you want to have multiple yaml output files, each holding the path to one profile?

No, at the moment you just can produce one result file. But we could update the output definition to a list if you think that it makes sense. 

Then the signature would be Fastq A -> [Profiling B]

> 3.If possible, I also copy the original output file of the tools into the mounted output directory. Useful if you don't trust my conversion into a profile. Should that be integrated into the yaml, or do we ignore that, because it is mainly for debugging purpose?

In future bioboxes releases we want to add a debug option but at the moment it would be enough to place them in the cache directory it it is mounted.

**Comment by sjanssen2** [comment]
@2:
The definition of the input yaml allowed for a list of multiple inputs, thus it would only make sense if the result is also a list of profiles. One could imagine that the user wants to pool all inputs, but I guess it would be more natural, if he/she does this prior to the input files and thus provides only a single pooled input fastq.
--> please make the output definition a _list_

@3:
would it hurt, if the original files end up in the /bbx/mnt/output directory? It would require some effort to change this in my images.

**Comment by pbelmann** [comment]
> @3:
> would it hurt, if the original files end up in the /bbx/mnt/output directory? It would require some effort > to change this in my images.

Yes you can place them in /bbx/mnt/output . Many other tools like quast biobox is doing the same.

**Comment by sjanssen2** [comment]
changed Utils.pm such that prior to execution a check is made, if /bbx/mnt/output/biobox.yaml can be touched. If yes, whenever one of the tasks has been executed, two according lines "path" and "format" are added to the growing YAML reporting file until all tasks have been completed. 
Should the container be killed meanwhile, this file will contain reports about tasks that could be executed so far, but nothing about those tasks that didn't make it - cause the container was stopped.
Is it OK this way? Or better produce the YAML only if everything is complete and thus eventually throw away reports about those tasks that have been executed?

**Comment by pbelmann** [comment]
I think it is ok if a container produces an output even if it means that it is just a part of the task. 
Therefore we have the log.txt where a user could lookup eventual errors reported by the tool.

**Comment by sjanssen2** [comment]
Cool. Thus, I can close this issue
