### ISSUE TITLE
metaphyler should produce a log file

### ISSUE THREAD

**Issue by pbelmann** [CAMI-challenge/docker_profiling_tools#4]
If /bbx/metadata is mounted it should produce a log file inside the directory:
https://github.com/pbelmann/rfc/blob/feature/new-profiling-inteface/container/profiling/rfc.mkd#mounts-1

Example: https://github.com/bioboxes/velvet/blob/master/assemble#L41-L43

**Comment by sjanssen2** [comment]
Do I get it right that it means to redirect STDERR into a file log.txt, which is located at $METADATA?

**Comment by pbelmann** [comment]
stderr and stdout are redirected to $METADATA

**Comment by sjanssen2** [comment]
updated Utils.pm, such that prior to execution a check is triggered if a directory /bbx/metadata/ exists and is writeable. If yes, STDERR and STDOUT of task.pl (which is the entrypoint of the container) is redirected into /bbx/metadata/log.txt
