### ISSUE TITLE
Register tools on Dockerhub

### ISSUE THREAD

**Issue by pbelmann** [CAMI-challenge/docker_profiling_tools#5]
We can register multiple images based on one github repository. But before we can start we should fix the following build error:
https://hub.docker.com/r/pbelmann/metaphyler/builds/bsav5gtwv9uou8fara4pyc8/

This happens because Dockerhub does not build from the root of the repository but from the /metaphyler folder. 

If we can fix this, we just have to move/fork this repo to cami-challenge and start registering containers on dockerhub.

**Comment by sjanssen2** [comment]
when I push something to my git repository an automated build is triggered. Do you know if I can abort a build that is in progress?

**Comment by pbelmann** [comment]
No it is not possible. But it doesn't matter. It will fail but your previous (working) version can still be used.

**Comment by pbelmann** [comment]
So far it is possible to register Dockerfiles with a custom name and if we place them at the root of the repository it will work out with your current dev structure. However there is a bug on dockerhub or at least it seems to be one: https://hub.docker.com/r/pbelmann/metaphyler4/builds/bxpnwy2dbmwn7etzajyfjrj/

**Comment by sjanssen2** [comment]
I am just about to test the same idea :-/

**Comment by pbelmann** [comment]
Yes please continue. Dockerhub is a distrbuted service. Maybe it does not fail all nodes.

**Comment by sjanssen2** [comment]
same problem for me :-( https://hub.docker.com/r/stefanjanssen/docker_profiling_tools/builds/butp4pqtchty8bandft726n/
But what if I do not ADD these files, but download them from the git repository?

**Comment by pbelmann** [comment]
Yes you could try this. 
We could put your scripts in separate repository and register it on docker hub again.
This way we can on dockerhub set a hook to your script container. When you update your scripts, all the other containers (metaphlan, amphora, etc.) will be updated too.
Maybe you could try this with one or two images. And if it works we move everything to cami and register it there.

**Comment by sjanssen2** [comment]
Here is my quick and dirty workaround for autobuilds: The context for the Dockerfile is now the subdirectory of a tool, e.g. metacv instead of the base directory of the git repository. The shared files are not ADDed from ../ but downloaded from the git repository. This works fine, but might be confusing, because changes in e.g. ../Utils.pm will become active only after pushing the change to github!
